CREATE TABLE MEMBERS(
USERNUM NUMBER(6),
USERID NVARCHAR2(20),
USERPW NVARCHAR2(20),
USERNAME NVARCHAR2(20),
USERPHONE NVARCHAR2(13),
USERGENDER NVARCHAR2(1),
USERADDR NVARCHAR2(200),
USEREMAIL NVARCHAR2(200),
USERDOMAIN NVARCHAR2(100)
);

ALTER TABLE MEMBERS
MODIFY USERPW NOT NULL
MODIFY USERNAME NOT NULL
MODIFY USEREMAIL NOT NULL
ADD CONSTRAINT UK_USERID UNIQUE(USERID)
ADD CONSTRAINT PK_USERNUM PRIMARY KEY(USERNUM);

SELECT * FROM MEMBERS;

CREATE TABLE BOARD(
BNUM NUMBER(8),
BUSERNUM NUMBER(6),
BTITLE NVARCHAR2(100),
BCONTENTS NVARCHAR2(2000),
BDATE DATE,
BHITS NUMBER
);
ALTER TABLE BOARD
ADD CONSTRAINT PK_USER_BNUM PRIMARY KEY(BNUM)
ADD CONSTRAINT FK_BUSERNUM FOREIGN KEY(BUSERNUM) REFERENCES MEMBERS(USERNUM)
MODIFY BTITLE NOT NULL
MODIFY BDATE DEFAULT SYSDATE;

SELECT
    *
FROM BOARD;
COMMIT;

